### ISSUE TITLE
Mustache module not found

### ISSUE THREAD

**Issue by silversonicaxel** [silversonicaxel/gherkin-detailer#1]
Once the application is installed and after trying to be executed, the Mustache module cannot be found inside the project

`internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'mustache'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (....)`

**Comment by silversonicaxel** [comment]
Solved bringing some dependencies from `devDependencies` to `dependencies` in package.json
